### ISSUE TITLE
One JavaScript Style to Rule Them All

### ISSUE THREAD

**Issue by y12studio** [g0v/labor-standards-tw#12]
提議支援standardjs標準格式。現況編輯後commit前先由eslint檢查再根據錯誤逐行逐格修改。如支援standardjs，許多編輯器內有標準格式化工具，不需去逐行逐格修改，增加生產效率。

JavaScript Standard Style  https://standardjs.com/readme-zhtw.html

**Comment by yurenju** [comment]
@y12studio 你可以送一個 pr 來改用 standardjs。

不過現在已經用 eslint 設定好規則跟在 travis 檢查了，我用的編輯器 vscode 如果寫的時候有沒遵守的地方也會顯示錯誤不用等到 commit 前才會知道，eslint 也有指令可以自動修正，看起來似乎 standardjs 可以做的 eslint 都可以做（除了 standardjs 不需要設定檔案，我看起來是好壞參半，畢竟大家都有自己的喜好）

不過我們還是可以試試 standardjs，如果你想新增 standardjs 請開一個 pr 做下面幾件事情：
1. 安裝 standardjs 到 `devDependencies`
2. 完整的移除 eslint 如 package.json 裏頭有相依到 eslint 的部分與 .eslintrc.js
3. package.json 裡面指定 `npm run lint` 應該指向 standardjs
4. 目前專案裡的所有 js 應該要改成符合 standardjs 的格式。

前情提要一下，之前我在 pr #9 的時候針對那個 pr 提了一些疑問，最後有點不歡而散，我自己檢討了一下或許比較寬鬆的接受 patch 會比較好，所以接下來的 issue 跟 pr 我會比較寬鬆的接受。

**Comment by y12studio** [comment]
@yurenju  standardjs剝奪設定自由換來各專案間較強一致性這件事，對於特定專案的好壞需由專案原開發者來確認，所以在動手PR實做前先提議看是否有共識，畢竟先參與專案開發者有其習慣換格式不一定好。

**Comment by yurenju** [comment]
@y12studio 我們可以試試 standardjs :D

**Comment by yurenju** [comment]
@y12studio 收了，感謝！
