### ISSUE TITLE
測試與研究 cucumber.js

### ISSUE THREAD

**Issue by yurenju** [g0v/labor-standards-tw#13]
這幾天看了 [cucumber.js](https://github.com/cucumber/cucumber-js) 之前在 slack 有討論要用什麼格式讓一般人也可以 contribute test case，看起來 cucumber 的格式不涉及實作，似乎會比較適合讓較沒程式背景的人參與。

例如目前的其中一條 test case:

```javascript
descrbe('薪資給付', () => {
  describe('加班費', () => {
    describe('一般加班', () => {
      it('月薪制勞工，平均時薪 150 元，平日工作 10 小時，其加班費為 400');
    });
  });
});
```

寫成 cucumber 的 feature 會變成這樣：

```cucumber
功能: 薪資給付

  情境: 員工的加班費計算
    假如 一個員工平均時薪 150 元，
    而且 平日工作 10 小時
    那麼 他的加班費為 400 元
```

這樣我覺得會比較好撰寫，不過還是要問一下不寫程式的人。

**Comment by yurenju** [comment]
試了一下，先放在 [yurenju/labor-standards-tw/cucumberjs](https://github.com/yurenju/labor-standards-tw/commit/1b55554298b670ff5ce08851b491ffaf544d5908)

測試案例看起來會長這樣

![image](https://cloud.githubusercontent.com/assets/22155/25416527/d15e5f42-2a70-11e7-98c2-c2a027938e09.png)

如果定義了 feature 檔案，但是沒有實作，他就會給個空實作讓你可以填你要的程式碼進去

![image](https://cloud.githubusercontent.com/assets/22155/25416628/55b72e9a-2a71-11e7-9b30-6a0118220da2.png)

跑起來會長這樣

![image](https://cloud.githubusercontent.com/assets/22155/25416518/c1812de8-2a70-11e7-8c48-0c3758dbae85.png)

一般使用者只要填第一份就好了，應該會比較好寫。 @chuck-lee 覺得如何？

**Comment by chuck-lee** [comment]
可以試試看
不過看起來會需要很多額外規範，像是一個檔案裡的Given, When和Then可能不能太多種；每個Given, When, Then的描述句要有特定格式，其實感覺跟寫code差不多了

**Comment by yurenju** [comment]
他是可以 `and` 一直加條件上去 XDD

比如說這樣

```cucumber
  場景: 違法狀況下平日的加班費
    假設 一個月薪制的勞工，平均時薪為 150 元
    當 他平日工作 13 小時
    那麼 他的加班費為 1150 元
    而且 違反勞基法 32 條

  場景: 假日 (holiday) 的加班費
    假設 一個月薪制的勞工，平均時薪為 150 元
    當 他同意於假日上班
    而且 工作時間 2 小時
    那麼 根據勞基法 39 條與台八十三勞動一字第 102498 號函
    同時 他的加給工資為 1200 元

  場景: 例假日「無」天災、事變或突發事件而工作
    假設 一個月薪制的勞工，平均時薪為 150 元
    當 雇主要求於例假日工作
    而且 徵得勞工同意
    而且 工作時間 2 小時
    但是 沒有發生天災、事變或突發事件
    那麼 他的加給工資為 1200 元
    並且 無額外補休
    並且 為違法加班
    同時 依據勞基法 79 條
    並且 罰款為 20000 至 100000 元
```

**Comment by yurenju** [comment]
把加班費的部分轉過去了，規格看起來會像這樣：

https://github.com/yurenju/labor-standards-tw/blob/cucumberjs/features/overtime-pay.feature

測試案例的實作看起來會像這樣：

https://github.com/yurenju/labor-standards-tw/blob/cucumberjs/features/step_definitions/pays_steps.js

目前覺得有好有壞，好處當然在可以讓一般人參與，壞處是每個測試案例沒像以前這麼好懂。比如說這個測試案例：

```javascript
describe('紀念日、節日、勞動節 (holiday)', () => {
  it('經勞工同意後可於節日上班，以平均時薪 150 元計算並工作 2 小時，加給工資 1200 元', () => {
    const consent = true
    let result = std.overtimePay(150, 2, std.HOLIDAY, consent)
    expect(result.value).eq(1200)
    expect(result.reference[0].id).eq('LSA-39')
    expect(result.reference[1].id).eq('台八十三勞動一字第 102498 號函')
  })
})
```

原本還算是蠻清晰易懂的，但是換成 cucumber 之後，條件就會被拆到很多個不同的 function 裡面，規格的部分還是蠻清楚的： 
```cucumber
  場景: 國定假日的加班費
    假設 一個月薪制的勞工，平均時薪為 150 元
    當 在國定假日
    而且 該勞工同意上班
    而且 工作 2 小時

    那麼 根據 "勞基法 39 條"
    而且 根據 "台八十三勞動一字第 102498 號函"
    同時 他的加給工資為 1200 元
```

但是實作的部分就有點沒那麼清楚
```javascript
  Given('一個月薪制的勞工，平均時薪為 {int} 元', function (int) {
    this.hourly = int
  })

  When('在國定假日', function () {
    this.dayType = std.HOLIDAY
  })

  When('該勞工同意上班', function () {
    this.consent = true
  })

  When('工作 {number} 小時', function (number) {
    this.workHours = number
    this.result = std.overtimePay(this.hourly, this.workHours,
                                  this.dayType, this.consent, this.accident)
  })

  Then('他的加給工資為 {int} 元', function (int) {
    expect(this.result.value).eq(int)
  })
```

不過好處是他的條件是可以不同測試案例之間共用的，按照目前的測試結果我應該還是會改用 cucumber，看看有沒有辦法讓更多人一起來參與寫測試案例。
