### ISSUE TITLE
產假薪水計算方式可能有誤

### ISSUE THREAD

**Issue by chuck-lee** [g0v/labor-standards-tw#19]
現行法沒有規定一個月等於四週，但有規定一個月等於30天（[民法第123條](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=B0000001&FLNO=123)）
因此週薪計算不能將月薪除以四，而應該是月薪除以30再乘以7。
因此在test case裡的產假的薪水，週薪是8400而不是9000；所以受僱未滿六個月及滿六個月的合法薪資應該分別為33600及67200。
https://github.com/g0v/labor-standards-tw/blob/master/features/female.feature#L19
https://github.com/g0v/labor-standards-tw/blob/master/features/female.feature#L26

**Comment by yurenju** [comment]
天阿，這也太細了 XDD
話說這個討論的網址，應該要被寫進 test case 的附註內
之後才會知道要回來看這個
