### ISSUE TITLE
特休日加班的加班費計算有誤

### ISSUE THREAD

**Issue by chuck-lee** [g0v/labor-standards-tw#21]
時薪150元，於特休日加班8小時的加班費應該是1200元
https://github.com/g0v/labor-standards-tw/blob/master/features/paid-leaves.feature#L43
https://github.com/g0v/labor-standards-tw/blob/master/features/paid-leaves.feature#L52

**Comment by yurenju** [comment]
@chuck-lee 修了，謝啦！
