### ISSUE TITLE
Review request for '月薪制勞工，平均時薪 150 元並工作 10 小時，加給工資 1800 元（勞基法 39, 40 條）'

### ISSUE THREAD

**Issue by yurenju** [g0v/labor-standards-tw#4]
@chuck-lee  可以幫我看一下這條嗎？不確定我算對還算錯

https://github.com/yurenju/labor-standards-tw/blob/master/test/integration/pays.test.js#L82-L91

**Comment by chuck-lee** [comment]
要看是合法加班還是違法加班
可以參考這篇報導的圖
http://www.appledaily.com.tw/realtimenews/article/new/20161221/1017826/
合法的話是2400+補休，不合法的話是2100
（例假日根本沒有合法加班的誘因啊 XD）

**Comment by yurenju** [comment]
這張圖好像蠻適合寫成 test case 的XDDD

**Comment by yurenju** [comment]
在 commit 6d1d9fec4d38105f985ffe3592812f9610db3c1b 修好了。
